name: Waka Readme Stats

on:
  schedule:
    - cron: '0 0 * * *'  # 每天更新一次
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.wakatime_api_key }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "True"  # 显示总编码时长
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
