# see https://github.com/athul/waka-readme
name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# 关键：给 workflow 授予写入仓库内容的权限
permissions:
  contents: write

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.wakatime_api_key }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME_RANGE: last_30_days
          SHOW_TOTAL: true
          SHOW_TITLE: true
